store_url_map = {
    "Walmart": "https://www.walmart.ca",
    "Costco": "https://www.costco.ca",
    "Sobeys": "https://www.sobeys.com",
    "Loblaws": "https://www.loblaws.ca",
    "Metro": "https://www.metro.ca",
    "No Frills": "https://www.nofrills.ca",
    "FreshCo": "https://www.freshco.com",
    "Real Canadian Superstore": "https://www.realcanadiansuperstore.ca",
    "Food Basics": "https://www.foodbasics.ca",
    "Whole Foods": "https://www.wholefoodsmarket.com/stores",
    "IGA": "https://www.iga.net",
    "Maxi": "https://www.maxi.ca",
    "Provigo": "https://www.provigo.ca",
    "Atlantic Superstore": "https://www.atlanticsuperstore.ca",
    "Co-op Atlantic": "https://www.coopatlantic.ca",
    "Save-On-Foods": "https://www.saveonfoods.com",
    "Thrifty Foods": "https://www.thriftyfoods.com",
    "Buy-Low Foods": "https://www.buy-lowfoods.com",
    "Fortinos": "https://www.fortinos.ca",
    "Longo's": "https://www.longos.com",
    "Highland Farms": "https://www.highlandfarms.ca",
    "Choices Markets": "https://www.choicesmarkets.com",
    "Nature’s Fare Markets": "https://www.naturesfare.com",
    "Blush Lane Organic Market": "https://www.blushlane.com",
    "Amaranth Foods": "https://www.amaranthfoods.ca"
}
